kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: testing
  image: wintercdo/code-dot-org:0.7
  environment:
    CLOUDFRONT_KEY_PAIR_ID:
      from_secret: CLOUDFRONT_KEY_PAIR_ID
    CLOUDFRONT_PRIVATE_KEY:
      from_secret: CLOUDFRONT_PRIVATE_KEY
    PROPERTIES_ENCRYPTION_KEY:
      from_secret: PROPERTIES_ENCRYPTION_KEY
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  commands:
    - pwd
    - whoami
    - id -u
    - id -g
    - ls -alh
    - sudo chown -R circleci:circleci .
    - /entrypoint.sh docker/unit_tests.sh

trigger:
  branch:
  - drone-old